services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    - /sys/fs/cgroup:/cgroup:ro
    command:
    - --housekeeping_interval=15s
    - --docker_only=true
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - ./grafana:/var/lib/grafana
    - /var/run/docker.sock:/var/run/docker.sock:ro

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - ./homeassistant:/config
    - /etc/localtime:/etc/localtime:ro

  loki:
    command:
    - -config.file=/etc/loki/local-config.yaml
    container_name: loki
    image: grafana/loki:latest
    ports:
    - 3100:3100
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    - ./loki/data:/loki

  node-exporter:
    command:
    - --path.procfs=/host/proc
    - --path.rootfs=/rootfs
    - --path.sysfs=/host/sys
    - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    container_name: node-exporter
    image: prom/node-exporter:latest
    ports:
    - 9100:9100
    restart: unless-stopped
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro

  npm:
    container_name: nginx-proxy
    image: jc21/nginx-proxy-manager:latest
    ports:
    - 80:80
    - 81:81
    - 443:443
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - ./nginx/data:/data
    - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
    - pihole

  pihole:
    container_name: pihole
    environment:
    - TZ=Europe/London
    - FTLCONF_webserver_api_password=bobmarley
    - FTLCONF_dns_hosts=192.168.0.38 prometheus.home;192.168.0.38 grafana.home;192.168.0.38 loki.home;192.168.0.38
      npm.home;192.168.0.38 pihole.home;192.168.0.38 home.home;192.168.0.38 portainer.home;192.168.0.38
      containers.home;192.168.0.38 homeassistant.home;192.168.0.38 data.home;192.168.0.38
      grafana.home.net;192.168.0.38 loki.home.net;192.168.0.38 npm.home.net;192.168.0.38
      pihole.home.net;192.168.0.38 home.net;192.168.0.38 portainer.home.net;192.168.0.38
      containers.home.net;192.168.0.38 homeassistant.home.net;192.168.0.38 data.home.net;
    image: pihole/pihole:latest
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 8080:80/tcp
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - ./pihole/etc:/etc/pihole
    - ./pihole/dnsmasq:/etc/dnsmasq.d

  portainer:
    container_name: portainer
    environment:
    - CONTROLLER_TRUSTED_ORIGINS=http://containers.home,https://containers.home
    image: portainer/portainer-ce:latest
    ports:
    - 9000:9000
    restart: always
    security_opt:
    - no-new-privileges:true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./portainer:/data

  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    container_name: prometheus
    dns:
    - 100.70.68.91
    - 100.100.100.100
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    user: root
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus/data:/prometheus
    - ./prometheus/targets.json:/etc/prometheus/targets.json
    - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
    - cadvisor
    - node-exporter

  promtail:
    command:
    - -config.file=/etc/promtail/config.yml
    container_name: promtail
    image: grafana/promtail:latest
    labels:
    - prometheus_scrape=true
    ports:
    - 9080:9080
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    volumes:
    - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    - /var/log:/var/log:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
